name: Backend Chat CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: composer:latest

    steps:
      - uses: actions/checkout@v1
      - name: compose install
        run: |
          composer install
  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_TOKEN }} ${{ secrets.DOCKER_HOST }}
      - name: Build
        run: docker build -t taling/lapras-front . -f ./docker/
      - name: Tags
        run: |
          docker tag taling/lapras-front ${{ secrets.DOCKER_HOST }}/taling/lapras-front:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_HOST }}/taling/lapras-front:latest
