name: Lapras-frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  depoly:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_TOKEN }} ${{ secrets.DOCKER_HOST }}
      - name: Build
        run: docker build -t taling/lapras-front . -f ./docker/Dockerfile
      - name: Tags
        run: |
          docker tag taling/lapras-front ${{ secrets.DOCKER_HOST }}/taling/lapras-front:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_HOST }}/taling/lapras-front:latest
